---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: listmonk-secrets
  namespace: listmonk-prod
spec:
  encryptedData:
    LISTMONK_ADMIN_PASSWORD: AgB2kOWSWjt/+TN26QNVRfd1MfXIjKfDxO1juHWmxYw6tZYVPb1oHUJyTrtgRVqGaUxKqchgLfoR1sXQ7U6dRbpETKxH+YTXB3NkaJMNAmUwmsZqZtNeg+Yg3gSfXWuPBVW5oxvDQQG3JmUL2vacYqDrooIQvRXVGVrImf8G6n5YehEpRX27mtph+T9u8R9YphV2GJqsxCxBoVvJesURr3BqlVUSNsfTo7+riR6iKhB0ZGIWSamsBZ7KFHdO28vGAkoUS2075xuUILvrE5bWNDPFg9hGFruD+0ftMtnDVUZGRCVyIXfNkH0LigbMBlOo7AeYmMU2fp7jKhBiPWCaDYWQXvzKNDG6bKrv6IbT77D4F3SOolOvK0SJv3p4aP3QdEL60F980qa6u+xA/pxaZylAlaVCt39sEdmZe9uPvPZW9FER/0gJhdgRMGRL+zZk/+0p81FRfA52zygTDhZP2aO+9flt9qrrD7QXxxDD17HwxQHwQXSSGpBoh16FlM/VrZsBJjNSFppNE7bznQWeHGWfUbZgKzHlC6XXf4dTr/eMWcYIC1s/7SJ6NA6GGCA9ma3gYiN2x/hoWFsRMJEEGVyJxi7HjatlzefPfo6vUOIiWpJWDRjgXj0SoYjEDJfFTrL3GjgeguWMmEfR7YGpiNek1bQcqBla2Zi/O43HPwEyn70u0JuclF5ft4OHPp+kTO3Uf/dXtwDBVYKPH6VuNptVnl0gqFBNJvNqotkFes7QNA==
    LISTMONK_db__password: AgBzarytDR+tAFh7bIViPDc5l5xr47EgsPg91uHXvJFNzYKnXQFeoUetBP68GmoEcguuev06tQTCQreZL2nZ1YtbiDliyLMRUYoSxRBYUnKmLTFjOidLTQ817rCKvcEaOhG4VHHzjDNdXIbHxHZt0KLCUPa7g/wNRphMfKwq29F8NJ5HY6GUgfJDKSkNggTY86Hh6WF1C+EUclD9t87Ruj8FzRixtMax7tMPo2l/mN7s+SJ8ulSlMUWYdDVtEiK+M/qV9L7U2pUeZ37cww0g0U6t+SxLiOi8Af55SizxQoFIeV6PAWZ1r/Vtv0UaDdurvYUt/N57Qg13ItP+wEyaJMCr2VcoxhbKOWmHpaBo/fPyS4FF7hVXloSSpOjg0kPJS4MFWhPfydnyU4qqh6rmCxV0BFqxmVttVN181FvC6T3aNMiCNtM77M84Xm/VzPhGwHgrbUuzpUTU/+m3hl9xfbnoxktAVad6mNZHlnzfqZemfCAMhqnLBByvdGmu7DY65GwPRtgk69E1Z9Af6RnXx5g/xLxVzdcOSpNVFgWVVb2Jux51DetKO/ai9odU5lUlwJ6GEPKWhAML/G3+AaxWkEb1sB3XatqrDfmMOiUbrMsnEZoiM6VYKFpw7+TAtFqYMQj/u4HjDbhIdX6+tVP69ZWNR5lYtGf3a+aTOgdBxde2HYSI6OI77pdnc6IHAMXLv9JJkZGWGX+zWWmPKWMGCv6BFvEQJ1Kp410lYs7UTRWfkQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: listmonk-secrets
      namespace: listmonk-prod
    type: Opaque
