apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kaneo
  template:
    metadata:
      labels:
        io.kompose.service: kaneo
    spec:
      containers:
        - name: kaneo
          image: ghcr.io/usekaneo/kaneo:2.25.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KANEO_CLIENT_URL
              value: https://kaneo.gewis.nl
            - name: TZ
              value: Europe/Amsterdam
            - name: CUSTOM_OAUTH_CLIENT_ID
              value: kaneo-client
            - name: CUSTOM_OAUTH_DISCOVERY_URL
              value: https://auth.gewis.nl/realms/GEWISWG/.well-known/openid-configuration
            - name: CUSTOM_OAUTH_LOGOUT_URL
              value: https://auth.gewis.nl/realms/GEWISWG/protocol/openid-connect/logout
            - name: CUSTOM_OAUTH_SCOPES
              value: openid,profile,email
          envFrom:
            - secretRef:
                name: kaneo-secrets
          ports:
            - containerPort: 5173
              name: main
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: main
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: main
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      dnsConfig:
        options:
          - name: ndots
            value: '1'
