---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: kaneo-secrets
  namespace: kaneo-prod
spec:
  encryptedData:
    AUTH_SECRET: AgCvdYk2E8ZtTWMcUeXQg7uq3Ju9byYGmbpxKBtECrha8zO0uden0Lo18Cs+H4r3QsF+PRd5W2pebhkQY+7U7ZWQ6P9+SScRhk6ntNggTFK7gxS4xq0/5U5+ZI9x4lakcaW4lp3ScCJ6XO+f/x4OyyalG8KTuVInWJ/PGIizFV1o7nimqNN/N0gc20wdGToGIkW/eTG3rT70/KvLrL5Wsk/72EEk0h1jBW6PjDO/uSnJ9welLngynwqXYTSQxgwCJ8K5Tp4iGYWpGZTb23jqU0X+BI7glq89HS93pr3sEkph5lzMKV3pvFu+mTbOZ23ET/YykgVJgKOmbYHno0mwf/UjiC7Z5hVEUYnQpUKvMnwpl57cZIgydTE7OJQT0xYZ37C3QQPMPmmqX4/7WkkmCGXrbXgxUo80nIn8fiL5TjMYKf7rnzgsAcKowb3XiN6Zskw/gOruan6Ve11lB2vc0eyhtqbqak8VFNrCpw9XO+gh8tYKiZWFIKOZC5nv1e/RmPEPzFz2Ho+yiLhEqXms10PGLgu6/IVMiOTNfxriXDsgYwuUSm4xDquXg6l53wUsTo7GC5CIkk1hi+XNM9u6POd7IZzKD7zXYWvI/n7QfTJdwsXZJNCFiOcp1wgHi9NoNdg52Nj37+zuKQz5+93lqnWWWzYbRYe+k21MFGZyrDmz2HWlpUaPFXD/9tij3tBuM/eL+125IoV47AURoJaIrMLJfspKxHb4IYkW6lzJ0I2hcblfA/znCuOhydfyDsBxCB6pITMmGGETeODsAHAfh5fb
    DATABASE_URL: AgDZeSyOD5Zs6zxXENi7djzLGW5XnGv6m3X7VK5tXDcWgF/+PXIGSZIeWSSLVZxFRHalDDiU5LzQVvE+pgMolo1MEhCQRUwYQLuyZiCV2aGBfX3GK7BpvdVpEc+O3XgzENQRhSaGr1MhRgEV/adD5mh/eM0txBBWAz1VcoR4PStaqkBpYf8e8a6v2Awf4TrFgYFKaPci0zbLVUbszCPfWvGSOOyUKkGbO62YMJl7iiVOXb2Blw+lCbWazzafFOdFH3/mpx1WIxBB+eXdI5vxFZbChep/Bp/JvxZhByZXpo5XWXRRulEZ22zPFYNLeBTUbFu5U+ez18rg/uS0XLaGWShGFTGOb+mtTHgn5t/RDzbV0q05J7lv+/Jip7ZWf1EjhjKv7nKmv09lIUoYmgR5CTik8wOSoZsQwIJ+JYPh30ww6eODyPbLO27xHMUsskvIkZL56+ahLKDcAeh8X0ARB2ikiz6honlD1a7rIHnqQ8LhRD00lKe8EhJnsFjxS5bq8Gi6hr5DTi+ecYGXlH+s0g+TKT8bRKF9SWcRNAmmqTyPi0USKpTRGeiRdd8XtuI+5WZF2Ek+K3JZNWxn1SicGk1JRzpHnumy+s+1TlQDJqpGQzX1mM4bWsLkRqUBF7d1HiUgfIHdqQgVNrI7qlns0DHaWH/WrwPeBs6LLWykxHrZKSxLb3FuHz8yLc0yCkejbz2E0b7m3SQocMdECPxo8yMqu3BBsjHx8/yUuPSN6guB1tZMr2MpASRPLm7jC1dPWg9HiEUfs5jf0+BgjpbbavDgf70K/pF4Cryvm5Q8ilSXP2P+UrAPGvPhL42Ix+VSltMyvjj51vXojOU5f1lIGfGSogeGZA54Y5ZuOFnURXvR
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: kaneo-secrets
      namespace: kaneo-prod
    type: Opaque
