apiVersion: v1
kind: Secret
metadata:
  name: kaneo-secrets
  namespace: kaneo-prod
type: Opaque
stringData:
  AUTH_SECRET: REPLACE_ME
  # postgresql://svc-kaneo-prod:<password>@pg01.db.gewis.nl:5432/kaneoprod_db?sslmode=require
  DATABASE_URL: REPLACE_ME
  CUSTOM_OAUTH_CLIENT_SECRET: REPLACE_ME
