apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak-prod
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: REPLACE_ME
  KC_BOOTSTRAP_ADMIN_USERNAME: REPLACE_ME
  KC_DB_PASSWORD: REPLACE_ME
  KC_DB_USERNAME: REPLACE_ME
