apiVersion: v1
kind: Secret
metadata:
  name: osticket-secrets
  namespace: osticket-prod
type: Opaque
stringData:
  OST_ADMIN_PASSWD: REPLACE_ME
  OST_DBPASS: REPLACE_ME
  OST_DBUSER: REPLACE_ME
  OST_SECRET_SALT: REPLACE_ME
  SMTP_PASSWORD: REPLACE_ME
  SMTP_USERNAME: REPLACE_ME
