apiVersion: v1
kind: Secret
metadata:
  name: zulip-secrets
  namespace: zulip-prod
type: Opaque
stringData:
  MEMCACHED_PASSWORD: REPLACE_ME
  POSTGRES_PASSWORD: REPLACE_ME
  RABBITMQ_DEFAULT_PASS: REPLACE_ME
  REDIS_PASSWORD: REPLACE_ME
  SECRETS_auth_ldap_bind_password: REPLACE_ME
  SECRETS_email_gateway_password: REPLACE_ME
  SECRETS_email_password: REPLACE_ME
  SECRETS_memcached_password: REPLACE_ME
  SECRETS_postgres_password: REPLACE_ME
  SECRETS_rabbitmq_password: REPLACE_ME
  SECRETS_redis_password: REPLACE_ME
  SECRETS_secret_key: REPLACE_ME
  SECRETS_social_auth_oidc_secret: REPLACE_ME
  SECRETS_zulip_org_id: REPLACE_ME
  SECRETS_zulip_org_key: REPLACE_ME
  SETTING_AUTH_LDAP_BIND_DN: REPLACE_ME
  SETTING_EMAIL_GATEWAY_LOGIN: REPLACE_ME
  SETTING_EMAIL_GATEWAY_PATTERN: REPLACE_ME
  SETTING_EMAIL_HOST_USER: REPLACE_ME
  SETTING_NOREPLY_EMAIL_ADDRESS: REPLACE_ME
