---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: oidc-secret
  namespace: slugshrink-prod
spec:
  encryptedData:
    pluginSecret: AgDjeJx/E0JLet+sv6wzXgmxu6Ao1OEibu1QqszUmhtD+ITDF8Dl9YKT+c/ZR8PSvFJC2VVR741R4ualdbjrjlJkruMj0FcbQ0mT50p0/dGKOO99LExHnl2HYDq8BYhIvPQpuG5C7r7f+6BcxA+q/lU+zaQMwP0PizdLoXpsLObVW+WfbLdhnmmSVmSBEHm9b1lKTXKos4iplq8E7bbBJ/F2k2ffU7vNewydoc4SSwQ5Sgw6UXiEAqv/dQYYxoMdLj6dkM8Qi0BJUwbdElOqwYhmcIIHWhgIICsksgC1SqffqyTSYnHTenrX3+uKEgSMQDuuRPrgeCNX+1XCrwN2XcIKrPnJ3plIGwtjfmQx+tgHoZY1quQgiLn38rnCTmT9kwHYWNWx9gX7a3+xpKepjTWM2M8pOo0C9YlOZJSJ1NVfSD06v33IR8Paalrp9WItynrLWhfRUAJ3iop7e5iL7FQt0Fw7hQmcQUqOw+h/pMVFt8DrXjTsam54p1H9C6OLpUF7mTwNbxpn499i1Jko4WYVUvEC+dZquai+cEgO1vAiSxV+qZ6KmbyhMXrRBeiYZZeObPj1fzVHW3HEC7PbsqxCfxcR4cAZX6x2cLnCYdGLwl2cz2nf3pTea6f6zCsXTJBgfeHNajyY6qP0FSF8yTleasNIm8Ot1fkmueI748427YKVIe23X7DsfZPuQvTAQfiUZKyc7ynEIuzl7559AluLcjove5+yzKZ7zbQVNt8HLQ==
    providerClientSecret: AgCs1S7dlX+QDuUpEcp9evIeqOEs3Ovns+cijXpjOWM4+8iLuGGnmYmDqrzuC3EILjlyXIvHYRrd7gC3Dyojv8QjeS6z7Scc3n1oXn60zXzyM3UEGNjNIH7vIklXFCEv9KQ5UR3lD+FIEW5qEiWhiuIfNekdrDV3UEGzgzvhRGefluknh1OAZxRATjaFVzj0k/YPmiE5SDU0I5mE2yAuKLbCT7SeCoG7VBjulb8xDQQxr0QDtKBQ2tctjvlKntnd2HWMAq76N3S6wUTwRhGxn2PXwOh76svkYHYuRkGZ2B/UddquCQKWu1StsImKqXj3uf4GvEj7m/vN+rrat3f4/hjz8Bl+UPntIAAuyV4cHCq21waaHwxpt6kdDn6qTiCCCOAng103blKTDXgbztd7hDntJ5Hz9DdWX1+KaGu1FInycA9XtyXkAxucyeHbOw6FG7rVXmjVaBHI8QlA7XIGJWgWEvTIeO8wsOpekpw9psSnRlbAPoLxoUYf/C3E0AUr6JDxcGm41EVK7254bHSgleyg4TjboldayHeL8xltVkpp6FmfeKlPLV5APZe5n/TsRDqJTVCrjgJW5ZR0OXfN5Fnx1n9ZGP0flRCz7thWrOsJjqNNrilfEq2yzokJiqrAjT+ADaLE+8jyQVrapi61txpsVLL6qs5RNENszVo4IHz0cbzMK4upouPGTFsM7cJ3K+kSfVmqP+8TVN6UCqsHePO22bySnL17j7ZPu94dw5nLIw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: oidc-secret
      namespace: slugshrink-prod
    type: Opaque
