---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: slugshrink-secrets
  namespace: slugshrink-prod
spec:
  encryptedData:
    DB_PASSWORD: AgDkLwpg9mBb6GAK6O6l9+eifAkho7WD1aE9B2FvE0Vs0v+j7Y3lidJYaR3YOKmKUZhLRDHSRz+Qi/1KVg//tSK8s8TDku0nHN3Y71ZQzdLIMFVs3q5QYRWgLXaRjCEHz7xprXY+DmvszEEW3eJwrr+R1/zUyzoePupZlct1djMSyz+rsoCcnITgXurO7Y5+j6vRcmh1qG+T4cJR8bEkAajuRCrBkGLPvzvZSNwpSiIHjErFPMqc4yaLYRRKpQl1Xow/tK+WJDMdSnfmVsyBEZHh7+RWSp2JwzfbJvaF5Og6y0+gHmgSGUY2fMfMp1OOXf/llLvVxISd0At5X2qyW6tyvn/r8G6cp4iSUaTQdBfCvdPtHBaNHvLscsAzFtR/poPOkRqVmpTH7Xnsl5FiAtdbt1BDIhASPxupawS9syI78bJp0EOPNkM60B84SlCJfZy9HQalnoX10AlXZvxifYgKwnWNBcIDNvP8NRi6PBoD1/t8dOYbHQPrAqV8gRa+aIofdbax47QTVI+Ipxwh/UrDQ7yFqA2tetIwSXrx4sQtlSiV+xDCQfCegJup/xjldNdjusr8JHT5qaSOlH2D3+peUaXjskvGGaqLoMdD3kehnJ0ZQuVaymAzNz3JgaCnh97sMoWVrElyUyD9VTm2R5Vuv11n08E+T0knz1C5CI3l0Q+nEXvj08F7+fabM0zyFRVa0qmDX1+OratDtt/V2OXGBeMfoE8foTVxBM6xf/P5iwTWHu6XWivyKrokX6N/eChSU17oU5griyMqV0Dc6NDX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: slugshrink-secrets
      namespace: slugshrink-prod
    type: Opaque
